1WIDTH80:PALETTE0,0:PALETTE9,27:ONBRKGOTO3000:DIMS$(6):FORI=1TO6:READS$(I):NEXTI:O$="E F F#G G#A A#B C C#D D#E F F#G G#A A#B C C#D D# E ":DIMI$(9),Q$(9):FORI=1TO9:READI$(I),Q$(I):NEXTI
10PRINT:PRINT"Chord";:INPUTA$:PRINT:FORI=1TO6:IFMID$(A$,I,1)="X" THENPRINT"X"; ELSEPRINT" ";
11PRINT"  ";:NEXTI:PRINT:PRINT"+--+--+--+--+--+":FORI=1TO5:PRINT"!  !  !  !  !  !":FORS=1TO6:F=VAL(MID$(A$,S,1)):IFF=I THENPRINT"O"; ELSEPRINT"!";
12PRINT"  ";:NEXTS:PRINT:PRINT"+--+--+--+--+--+":NEXTI:C$="":R$="":FORS=1TO6:S$=MID$(A$,S,1):IFS$="X" THENGOTO20
13F=VAL(MID$(A$,S,1)):N$=MID$(S$(S),F*2+1,2):T$=N$:IFRIGHT$(N$,1)=" " THENN$=LEFT$(N$,1)
14IFINSTR(C$+" ",N$+" ")=0 THENC$=C$+N$+" ":R$=R$+T$
20NEXTS:PRINT:PRINT"Notes: ";C$:PRINT:F$="Unknown":FORI=1TO LEN(R$)STEP2:T$=MID$(R$,I,2):R=INT(INSTR(O$,T$)/2):I$="":FORN=0TO11:N$=MID$(O$,(R+N)*2+1,2):FORJ=1TO LEN(R$)STEP2:IFN$=MID$(R$,J,2) THENI$=I$+HEX$(N)
21NEXTJ:NEXTN:Q$="":FORK=1TO9:IFI$(K)=I$ THENQ$=Q$(K)
22NEXTK:IFRIGHT$(T$,1)=" " THENT$=LEFT$(T$,1)
23IFQ$<>"" THENF$=T$+Q$
24NEXTI:PRINTF$
100GOTO10
3000POKE&H71,0:EXEC&H8C1B
3001DATA"E F F#G G#A A#B C C#D D#E ","A A#B C C#D D#E F F#G G#A ","D D#E F F#G G#A A#B C C#D ","G G#A A#B C C#D D#E F F#G ","B C C#D D#E F F#G G#A A#B ","E F F#G G#A A#B C C#D D#E ","037A","m7","047A","7","047B"
3002DATA"maj7","057A","7sus4","027","sus2","037","m","047"," ","04A","7","057","sus4"
